//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordKeeping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Donor
    {
        public int DonorID { get; set; }
        public string Donor { get; set; }
    }
}
