//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordKeeping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_LeadOrgUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_LeadOrgUnit()
        {
            this.UNHabitatProjects = new HashSet<UNHabitatProject>();
        }
    
        public int LeadOrgUnitID { get; set; }
        public string LeadOrgUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNHabitatProject> UNHabitatProjects { internal get; set; }
    }
}
