//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordKeeping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UNHabitat_ProjectsEntities : DbContext
    {
        public UNHabitat_ProjectsEntities()
            : base("name=UNHabitat_ProjectsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_ApprovalStatus> A_ApprovalStatus { get; set; }
        public virtual DbSet<A_Country> A_Country { get; set; }
        public virtual DbSet<A_Donor> A_Donor { get; set; }
        public virtual DbSet<A_Fund> A_Fund { get; set; }
        public virtual DbSet<A_LeadOrgUnit> A_LeadOrgUnit { get; set; }
        public virtual DbSet<A_Theme> A_Theme { get; set; }
        public virtual DbSet<UNHabitatProject> UNHabitatProjects { get; set; }
    }
}
