//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordKeeping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNHabitatProject
    {
        public int ProjectID { get; set; }
        public string ProjectTitle { get; set; }
        public string PAASCode { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
        public Nullable<int> FundID { get; set; }
        public string PAGValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Country { get; set; }
        public Nullable<int> LeadOrgUnitID { get; set; }
        public string Theme { get; set; }
        public string Donor { get; set; }
        public string TotalExpenditure { get; set; }
        public string TotalContribution { get; set; }
        public string TotalContribution_TotalExpenditure { get; set; }
        public string TotalPSC { get; set; }
        public Nullable<int> DeletedRecord { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual A_ApprovalStatus A_ApprovalStatus { internal get; set; }
        public virtual A_Fund A_Fund { internal get; set; }
        public virtual A_LeadOrgUnit A_LeadOrgUnit { internal get; set; }
    }
}
